SavorySweets/Models/Treat.cs
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SavorySweets.Models
{
  public class Treat
  {
    public Treat()
    {
      this.JoinEntities = new HashSet<TreatFlavor>();
    }
    public string Name { get; set; }
    public int TreatId { get; set; }
  
    public virtual ICollection<TreatFlavor> JoinEntities { get; set; }
    public virtual ApplicationUser User { get; set; }  
  }
}

SavorySweets/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using SavorySweets.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace SavorySweets.Controllers
{
  public class FlavorsController : Controller
  {
    private readonly SavorySweetsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, SavorySweetsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public ActionResult Index ()
    {
      List<Flavor> model = _db.Flavors.ToList();
      return View(model);
    }

    [Authorize]
    public ActionResult Create()
    {
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Flavor flavor, int TreatId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flavor.User = currentUser;
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      if (TreatId != 0)
      {
        _db.TreatFlavor.Add(new TreatFlavor() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      ViewBag.Treats = _db.Treats.ToList();
      var thisFlavor = _db.Flavors
        .Include(flavor => flavor.JoinEntities)
        .ThenInclude(join => join.Treat)
        .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [Authorize]
    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [Authorize]
    [HttpPost]
    public ActionResult Edit(Flavor flavor, int TreatId)
    {
      if (TreatId != 0)
      {
        _db.TreatFlavor.Add(new TreatFlavor() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult AddTreat(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int TreatId)
    {
      if (TreatId != 0)
      {
        _db.TreatFlavor.Add(new TreatFlavor() { TreatId = TreatId, FlavorId = flavor.FlavorId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    [HttpPost]
    public ActionResult DeleteTreat(int joinId)
    {
      var joinEntry = _db.TreatFlavor.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      _db.TreatFlavor.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

SavorySweets/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using SavorySweets.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace SavorySweets.Controllers
{
  public class TreatsController : Controller
  {
    private readonly SavorySweetsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public TreatsController(UserManager<ApplicationUser> userManager, SavorySweetsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public ActionResult Index ()
    {
      List<Treat> model = _db.Treats.ToList();
      return View(model);
    }

    [Authorize]
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Treat treat)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      treat.User = currentUser;
      _db.Treats.Add(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      ViewBag.Flavors = _db.Flavors.ToList();
      var thisTreat = _db.Treats
        .Include(treat => treat.JoinEntities)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }
    
    [Authorize]
    public ActionResult Edit(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult Delete(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult AddFlavor(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat Treat, int FlavorId)
    {
      if(FlavorId != 0)
      {
        _db.TreatFlavor.Add(new TreatFlavor() { FlavorId = FlavorId, TreatId = Treat.TreatId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = Treat.TreatId });
    }

    [Authorize]
    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
      var joinEntry = _db.TreatFlavor.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      _db.TreatFlavor.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

SavorySweets/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@model SavorySweets.Models.Treat

<h2>Add Flavor to Treat: @Html.DisplayFor(model => model.Name)</h2>

<div class = "infoBox">

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.TreatId)

    <h3>@Html.Label("Select Flavor")
    @Html.DropDownList("FlavorId")</h3>
  
    <input type = "submit" value = "Save" class = "btn2" />  
  }
  
  @Html.ActionLink("Cancel", "Index", null, null, new { @class = "btn" })
</div>

<img src = "~/image/candy11.png">

SavorySweets/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model SavorySweets.Models.Treat

<h2>Add Treat @Html.ActionLink("Home", "Index", "Home", null, new { @class ="pageLink4" })</h2>

<div class = "infoBox">

  @using (Html.BeginForm())
  {
    <h3>@Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name, new { @class = "wordLink", required = "required" })
    </h3>
    <br>
    
    <input type = "submit" value = "Add Treat" class = "btn2" />
    @Html.ActionLink("Cancel", "Index", null, null, new { @class = "btn" })
  }
</div>

<img class = "image" src = "~/image/candy9.png">

SavorySweets/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model SavorySweets.Models.Treat

<h2>Treat @Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name) 
  
@Html.ActionLink("Home", "Index", "Home", null, new { @class ="pageLink4" })</h2>

<div class = "infoBox">
  <h3>Are you sure you want to <strong>DELETE</strong> this Treat?</h3>
  <br>

  @using (Html.BeginForm())
  {
    <input type = "submit" value = "Delete" class = "btn2" />
  }
  
  @Html.ActionLink("Cancel", "Index", null, null, new { @class = "btn" })
</div>

<img class = "image" src = "~/image/candy9.png"> 

SavorySweets/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@model SavorySweets.Models.Treat

<h2>@Html.Label("Treat Name"): @Html.DisplayFor(model => model.Name) @Html.ActionLink("Home", "Index", "Home", null, new { @class = "pageLink4" })</h2>

<div class = "infoBox">
  @Html.ActionLink("Treat List", "Index", null, null, new { @class = "btn" })
  @Html.ActionLink("Edit Treat", "Edit", new { id = Model.TreatId }, new { @class = "btn" })
  @Html.ActionLink("Delete Treat", "Delete", new { id = Model.TreatId }, new { @class = "btn" })

  @if (ViewBag.Flavors.Count == 0) 
  {
    <h4>No Flavor to Add Yet!</h4>
    @Html.ActionLink("Add Flavor to Store", "Create", "Flavors", null, new { @class = "pageLink2" })
  }
  else
  {
  @Html.ActionLink("Add Flavor to Treat", "AddFlavor", new { id = Model.TreatId }, new {@class = "pageLink3"})
  }
</div>

<div class = "detailBox">
  <img class = "image1" src = "~/image/candy4.png"> 

  @if(@Model.JoinEntities.Count == 0)
  {
    <h1>No Flavor <br>for<br> This Treat!</h1>
  }
  else
  {
    <h3>Flavors List for Flavor @Html.DisplayFor(model => model.Name)</h3>
    <ul>
    @foreach(var join in Model.JoinEntities)
    {
      <li>@join.Flavor.Name</li>
      @using (Html.BeginForm("DeleteFlavor", "Treats"))
      {
        @Html.Hidden("joinId", @join.TreatFlavorId)
        <input type = "submit" value = "Delete" class = "btn3"/>
      }  
    }
    </ul>
  }
</div>

SavorySweets/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model SavorySweets.Models.Treat

<h2>Edit Treat: @Html.DisplayFor(model => model.Name) @Html.ActionLink("Home", "Index", "Home", null, new { @class ="pageLink4" })</h2>

<div class = "infoBox">

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.TreatId)

    <h3>@Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name, new { @class = "wordLink", required = "required", })</h3>
    <br>
    <input type = "submit" value = "Save" class = "btn2" />
  }
  @Html.ActionLink("Cancel", "Index", null, null, new { @class = "btn" })
</div>

<img class = "image" src = "~/image/candy11.png"> 

SavorySweets/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using SavorySweets.Models;

<h2>Treats List</h2>

@Html.ActionLink("Add Treat", "Create", null, null, new { @class = "pageLink" })
@Html.ActionLink("Home", "Index", "Home", null, new { @class = "pageLink" })

<div class = "indexBox">
  <img class = "image1" src = "~/image/candy6.jpg" >

  @if (@Model.Count == 0)
  {
    <h1>Treat List <br>is<br>EMPTY!</h1>
  } 
  else
  {
    <h3>Click on Treat to See Details</h3>
    
    @foreach(Treat treat in Model)
    {
      <li>@Html.ActionLink($"{ treat.Name }", "Details", new { id = treat.TreatId }, new { @class = "linkWordColor" }) 
      </li>
    }
  }
</div>   